### PR TITLE
Fix dep flood and other np issues

### PR DESCRIPTION
**Pull request by prodhype**

### CODE REVIEW

**Comment by zeque92** [comment]
Hi prodhype,

Thanks so much for your fixes. For this one, I can see the issue with dtype, but why the change from **color += xxx** to **color = color + xxx**?

**Comment by prodhype** [comment]
> Hi prodhype,
> 
> Thanks so much for your fixes. For this one, I can see the issue with dtype, but why the change from **color += xxx** to **color = color + xxx**?

Fixes this issue:
```
File "/code/RealTime3DwithPython/RGB Sphere/RGB Sphere.py", line 907, in get_surface_color
    color += np.sum(image_array[x_right:x_left, y, :], axis=0)
numpy.core._exceptions._UFuncOutputCastingError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'
```

**Comment by zeque92** [comment]
> > Hi prodhype,
> > Thanks so much for your fixes. For this one, I can see the issue with dtype, but why the change from **color += xxx** to **color = color + xxx**?
> 
> Fixes this issue:
> 
> ```
> File "/code/RealTime3DwithPython/RGB Sphere/RGB Sphere.py", line 907, in get_surface_color
>     color += np.sum(image_array[x_right:x_left, y, :], axis=0)
> numpy.core._exceptions._UFuncOutputCastingError: Cannot cast ufunc 'add' output from dtype('float64') to dtype('int32') with casting rule 'same_kind'
> ```

Thanks. Works fine for me under Windows 11, Spyder 5.4.3, Python 3.11.4, NumPy 1.24.3. I suppose the caps issues in file names you raised are also on some other platform? Anyway, good to fix these, they just easily creep in there as I don't really see them...

To me, the **color += xxx** and **color = color + xxx** should be the same. I would be inclined to fix this by using (xxx).astype(np.int32) instead to avoid the casting error. Any comments?

**Comment by prodhype** [comment]
> Thanks. Works fine for me under Windows 11, Spyder 5.4.3, Python 3.11.4, NumPy 1.24.3. I suppose the caps issues in file names you raised are also on some other platform? Anyway, good to fix these, they just easily creep in there as I don't really see them...
> 
> To me, the **color += xxx** and **color = color + xxx** should be the same. I would be inclined to fix this by using (xxx).astype(np.int32) instead to avoid the casting error. Any comments?

I guess the big difference between our setups is that I run this on Ubuntu 22.04.2 LTS python 3.11.7 and numpy 1.26.2. Apparently Windows isn't big on case-sensitive filenames.

I don't think it matters the solution you go with, I have no strong feelings either way.

**Comment by zeque92** [comment]
> > Thanks. Works fine for me under Windows 11, Spyder 5.4.3, Python 3.11.4, NumPy 1.24.3. I suppose the caps issues in file names you raised are also on some other platform? Anyway, good to fix these, they just easily creep in there as I don't really see them...
> > To me, the **color += xxx** and **color = color + xxx** should be the same. I would be inclined to fix this by using (xxx).astype(np.int32) instead to avoid the casting error. Any comments?
> 
> I guess the big difference between our setups is that I run this on Ubuntu 22.04.2 LTS python 3.11.7 and numpy 1.26.2. Apparently Windows isn't big on case-sensitive filenames.
> 
> I don't think it matters the solution you go with, I have no strong feelings either way.

Thanks again.

**Pull request closed without merging**
